# ruff.toml

line-length = 100
target-version = "py310"

[lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E501"]                          # example: ignore long line warnings

[format]
quote-style = "double"
indent-style = "space"

exclude = ["reference_projects/**"]
